/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import control.CustomerController;
import model.Customer;

/**
 *
 * @author dangc
 */
public class Main extends javax.swing.JFrame {
    ArrayList<Customer> customers = new ArrayList<>();

    /**
     * Creates new form Main
     */

    public Main() {
        initComponents();
        // load data from CustomerController.loadData()
        customers = CustomerController.getCustomers();
    }

    public void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        model.setRowCount(0);
        for (Customer customer : customers) {
            model.addRow(new Object[] { customer.getId(), customer.getName(),
                    customer.getPrevReading(),
                    customer.getCurrReading() });
        }
    }

    public void calculateBill() {
        DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        model.setRowCount(0);
        for (Customer customer : customers) {
            model.addRow(new Object[] { customer.getId(), customer.getName(),
                    customer.getPrevReading(),
                    customer.getCurrReading(), customer.calculateBill() });
        }
    }

    public void calculateAvgBill() {
        double avgBill = CustomerController.calculateAvgBill();
        txt_AvgBill.setText(String.valueOf(avgBill));
    }

    public void findCustomerMaxBill() {
        Customer customer = CustomerController.findCustomerMaxBill();
        DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        model.setRowCount(0);
        model.addRow(new Object[] { customer.getId(), customer.getName(),
                customer.getPrevReading(),
                customer.getCurrReading(), customer.calculateBill() });
    }

    public void findCustomer() {
        int customerID = Integer.parseInt(txt_CustomerID.getText());
        while (txt_CustomerID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng");
        }
        Customer customer = CustomerController.findCustomer(customerID);
        if (customer == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng");
        } else {
            DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
            model.setRowCount(0);
            model.addRow(new Object[] { customer.getId(), customer.getName(),
                    customer.getPrevReading(),
                    customer.getCurrReading(), customer.calculateBill() });
        }
    }

    public void findIndustrialCustomerMaxBill() {
        Customer customer = CustomerController.findIndustrialCustomerMaxBill();
        DefaultTableModel model = (DefaultTableModel) CustomersTable.getModel();
        model.setRowCount(0);
        model.addRow(new Object[] { customer.getId(), customer.getName(),
                customer.getPrevReading(),
                customer.getCurrReading(), customer.calculateBill() });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();
        findIndustrialMaxBillButton = new javax.swing.JButton();
        loadDataButton = new javax.swing.JButton();
        calculateBillButton = new javax.swing.JButton();
        avgBillButton = new javax.swing.JButton();
        findCustomerButton = new javax.swing.JButton();
        findMaxBillButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_AvgBill = new javax.swing.JTextField();
        txt_CustomerID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TÍNH TIỀN ĐIỆN CHO PHƯỜNG LINH TRUNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CustomersTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Chỉ số đầu", "Chỉ số cuối", "Tiền điện"
            }
        ));
        CustomersTable.setRowHeight(30);
        jScrollPane1.setViewportView(CustomersTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1010, 280));

        findIndustrialMaxBillButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findIndustrialMaxBillButton.setText("Yêu cầu 6: Tìm KH \"Hộ sản xuất\" có tiền điện lớn nhất");
        findIndustrialMaxBillButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        findIndustrialMaxBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findIndustrialMaxBillButtonActionPerformed(evt);
            }
        });
        jPanel1.add(findIndustrialMaxBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));

        loadDataButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadDataButton.setText("Yêu cầu 1: Load dữ liệu");
        loadDataButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loadDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loadDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 310, -1));

        calculateBillButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calculateBillButton.setText("Yêu cầu 2: Tính tiền điện");
        calculateBillButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calculateBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBillButtonActionPerformed(evt);
            }
        });
        jPanel1.add(calculateBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 350, -1));

        avgBillButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        avgBillButton.setText("Yêu cầu 4: Tính trung bình tiền điện");
        avgBillButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        avgBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgBillButtonActionPerformed(evt);
            }
        });
        jPanel1.add(avgBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        findCustomerButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findCustomerButton.setText("Yêu cầu 3: Tìm KH theo mã");
        findCustomerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        findCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCustomerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(findCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 290, -1));

        findMaxBillButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findMaxBillButton.setText("Yêu cầu 5: Tìm KH có tiền điện lớn nhất");
        findMaxBillButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        findMaxBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMaxBillButtonActionPerformed(evt);
            }
        });
        jPanel1.add(findMaxBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 350, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Trung bình tiền điện:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 210, -1));

        txt_AvgBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_AvgBill.setName(""); // NOI18N
        jPanel1.add(txt_AvgBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 310, -1));

        txt_CustomerID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_CustomerID.setName(""); // NOI18N
        jPanel1.add(txt_CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã Khách hàng:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 270, -1));

        jTabbedPane1.addTab("Tính tiền điện", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản lý nhân viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findIndustrialMaxBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIndustrialMaxBillButtonActionPerformed
        // TODO add your handling code here:
        findIndustrialCustomerMaxBill();
    }//GEN-LAST:event_findIndustrialMaxBillButtonActionPerformed

    private void findMaxBillButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findMaxBillButtonActionPerformed
        // TODO add your handling code here:
        findCustomerMaxBill();
    }// GEN-LAST:event_findMaxBillButtonActionPerformed

    private void avgBillButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_avgBillButtonActionPerformed
        // TODO add your handling code here:
        calculateAvgBill();
    }// GEN-LAST:event_avgBillButtonActionPerformed

    private void findCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findCustomerButtonActionPerformed
        // TODO add your handling code here:
        findCustomer();
    }// GEN-LAST:event_findCustomerButtonActionPerformed

    private void calculateBillButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_calculateBillButtonActionPerformed
        // TODO add your handling code here:
        calculateBill();
    }// GEN-LAST:event_calculateBillButtonActionPerformed

    private void loadDataButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loadDataButtonActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
    }// GEN-LAST:event_loadDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomersTable;
    private javax.swing.JButton avgBillButton;
    private javax.swing.JButton calculateBillButton;
    private javax.swing.JButton findCustomerButton;
    private javax.swing.JButton findIndustrialMaxBillButton;
    private javax.swing.JButton findMaxBillButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadDataButton;
    private javax.swing.JTextField txt_AvgBill;
    private javax.swing.JTextField txt_CustomerID;
    // End of variables declaration//GEN-END:variables
}
